### ISSUE TITLE
[CH1][CH2] 빌드 공장 가동 3주차

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#581]
[피드백 엑셀파일](https://docs.google.com/spreadsheets/d/1x_Rz09V7zD9MRT8yy9H-mmbQ7r809jbHCKjPCP-icXE/edit?gid=1430539115#gid=1430539115)

가장 최신의 CH2 시스템 문서 [폴더](https://drive.google.com/drive/folders/1WKl1CqMziCgjphhlsZLk8dHLOuNYDUiX)에서 찾기

~역접속 글리치 (SLG와 럭키)~
~글리치 효과음 받아서 적용하기~
~사운드 리소스 이름에 [] 빼기~
~CI에 빌드 warning 체크~

---

### 우선순위 (CH1 퀄업 => CH2 개발)
1. 역접속 글리치
2. 텍스트애니메이션 손보기
3. 먼지 파티클 깔기
4. CH2 키 입력
5. CH2 맵 이동 (로그보다 맵 이동 먼저)

## 0801 목
- [x] 럭키 글자등장효과 제거
- [x] 마마고 컴퍼니 완공 후 파머 대사
- [x] 럭키 역접속 글리치 추가
- [x] SLG팩 역접속 글리치 추가
- [x] 역접속 효과음 추가
- [x] 사운드 리소스 이름에 `[]` 빼기
- [x] CH2 키 초기 세팅

## 0802 금
- [x] CI 오류 수정 ([해당 이슈](https://github.com/GG-Studio-990001/Grayed-Game/issues/593#issue-2444478234) 3, 4번)
- [x] CI 빌드 이름 수정 ([코멘트](https://github.com/GG-Studio-990001/Grayed-Game/issues/593#issuecomment-2265030742) 참고)
- [x] 맵 confiner 수정
- [x] 맵3 하단 오브젝트 콜라이더 수정
- [x] 먼지 파티클 ([이슈](https://github.com/GG-Studio-990001/Grayed-Game/issues/598))
- 2차
- [x] 동굴 BGM 이어서 틀기
- [x] 타이틀에서 CH1 넘어갈 때 볼륨 넘기기 (Save)
- [x] 탈출 효과음 안나옴
- [x] 탈출 이미지 안나옴 (흠 직접 빌드하니까 일단 됨..)
- [x] 타임라인 오디오트랙 볼륨 동기화 (Title)

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/f2d285d3-6bfa-47f5-8cda-120063f8359b)

대괄호를 넣지 말라는 워닝이 있어서 CH1에서만 쓰이는 파일들은 CH1 폴더를 만들고 이동시켰습니다.
리소스명들을 수정하는 김에 규칙을 지켜 수정해줬습니다.
`(말머리제거)이름_분류(_번호)`

ex) `[CH1] Mamago_Construction` => `Mamago_Construction_SFX`
`[CH1] SFX_Escape_03` => `Escape_SFX_03`

@Songkihwa 
다음에 리소스 새로 주실 때 규칙 참고 부탁드려요!

@팀원들
추후 빌드에 사운드 누락된 거 있으면 체크 부탁드려요!

**Comment by Songkihwa** [comment]
아하 다음부터는 대괄호 채널 번호 빼두겠습니다!!
