### ISSUE TITLE
마법의 소라고동

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#661]
# 마법의 소라고동

> 자잘한 기획 수정사항이나 자잘한 버그를 추적합니다.

![image](https://github.com/user-attachments/assets/64a922d3-003d-4299-8813-91fe0a298ab2)

현재 자잘한 기획사항이나 버그가 추적이 안되고 있습니다. 기존 방식인 엑셀을 활용했지만 지속적인 관리가 어려워서 깃허브로 통합하기로 결정했습니다.

이름은 **마법의 소라고동**

<details><summary>작성 방법</summary>
<p>

컨펌이 완료된 수정사항은 본문에 기재됩니다. 

ex)
- [ ] [CH1] 연출 위아래 영화 프레임 추가

이후 해당 내용을 바로 이슈화하여 작업자 할당을 진행합니다. 할당은 정기회의에서 진행

컨펌이 필요한 내용은 코멘트로 작성해주시면 됩니다. @fkdl0048 쉽게 결정 내릴 수 있는 내용은 바로 본문으로 올리고 연락드리는 방식으로 진행하고 논의가 필요하면 회의를 통해 내용을 다듬습니다.

코멘트에 작성해주실 내용은 버그, 수정하기로 했는데 추적이 안된 내용, 필요하다고 생각하는 내용 자유롭게 자유 형식으로 달아주세요.

한 가지 작업이 상정되면 해당 이슈를 바로 발행하여 작업자를 할당합니다. 예를 들어 CH1 대사 수정사항이 들어오면 확인 후 대사 작업자, 해당 스크립트 적용 작업자 2인을 Assigness로 넣어서 작업을 할당하고 기한을 정해드립니다.

</p>
</details> 

## 마법의 소라고동아 뭐해야하는지 알려줘~

<details><summary>0.6.0 이전</summary>

- [x] #663 (@wooyn730 , @Sumindd )
- [x] #665 (@jeongopo , @wooyn730 , @roweclaw )
- [x] #666 (@jeongopo , @wooyn730 , @Songkihwa , @roweclaw )
- [x] #680 (@wooyn730 , @vprwolf )
- [x] #704 (@wooyn730 )
- [x] #706(@wooyn730 @jeongopo @JIJI037 )
- [x] #708
- [x] #707
- [x] #729
- [x] #734
- [x] #761
- [x] #762
- [x] #763
- [x] #854
- [ ] [CH2] 접속게임 쉐이더 적용 및 해상도
- [ ] [CH1] 라플리 움직임 삭제
- [ ] [CH1] R2-Mon 순간이동 버그
- [ ] [CH2] 마우스 커서

</p>
</details>

**Comment by Sumindd** [comment]
![2024-09-12](https://github.com/user-attachments/assets/1a0e63be-f19a-438b-8215-98d424d1d877)
노트북 전체 화면으로 봤을 때도 스크립트 박스의 크기와 폰트가 좀 크다고 느꼈는데 팀원분들은 어떻게 느끼는지 궁금합니다. (특히 아트 직군 팀원들..)

**Comment by wooyn730** [comment]
소라고동 좋네요~~

> 스크립트 박스의 크기와 폰트가 좀 크다고 느꼈는데

저는 사이즈가 그냥 여유로운 느낌..? 엄청 큰지는 모르겠어요
다른 비주얼노벨 스크린샷과 비교해보면 확실히 알 것 같네요

**Comment by wooyn730** [comment]
### SLG 마마고 컴퍼니 건설 단계에 대해

(1)
마마고 부지?에 가까이 가서 스페이스를 연타하는 분들을 많이 봐서,
'~~~ 무너져있다' 이런 식의 상호작용 스크립트를 추가하면 좋을 것 같습니다.

(2)
현재 마마고 컴퍼니 스프라이트는 무너짐과 완공 뿐인데
중간에 건설 중인 스프라이트를 추가하면 좋을 것 같습니다.

### 다리에 대해

무너진 다리를 지을 수 있게 한 건 좋았는데, 팩맘을 너프? 시키면서 필요성이 많이 줄어서
지으면 파머가 무척 기뻐한다던가? 등의 이스터에그를 넣으면 좋겠습니다.

참고로 맵3에서 파머 상호작용 대사가 '헛둘헛둘'인데 이것도 수정되면 좋겠네요.
(원래는 땅을 판다는 컨셉이었던걸로 기억...)

추가로 다리짓기도 약간의 시간 또는 코인을 요구하는 것,
다리짓기 시 목재 20에 철 5 정도로 목재 위주로 요구하면 좀 더 현실적..?일 것 같네요
(나무다리니까)

**Comment by Sumindd** [comment]
### 폰트 크기 분석
![image](https://github.com/user-attachments/assets/28923d06-a69a-4a8b-af44-9adbefe0f1e2)
![image](https://github.com/user-attachments/assets/f8210438-b974-4cdc-a162-e7f142cc9b99)

일단 화면 비율이 제각각이라 정확한 측정은 아니고 그냥 가로 길이 맞춰서 대충 재봤습니다.
모바일 게임도 섞여 있어서 아마 기기에 적합한 비율도 따로 있을 수 있다는 점 감안해주세요!

전체적으로 폰트 큰 게임들이 인디 게임이거나 오래된 게임이라.... 저는 폰트 크기가 조금 더 작은 쪽이 이쁘지 않나 싶은데 어느정도는 취향의 문제라 다른 분들의 의견도 궁금하네요


### 마마고 컴퍼니 건설 단계
기획 회의에서도 관련 이야기가 나와 [CH1 아트 리소스 리스트](https://docs.google.com/spreadsheets/d/1xLu0o7xpz4A3foy7fB_kl-RDrlTBvMuX/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true)에 중간 단계를 추가해뒀습니다! (17,18)재료를 제출하면 건설 중인 모습으로 변경되고, 말풍선을 다시 눌러서 시간 단축을 해야 완전히 건설 되도록 기획 수정하려고 합니다. 
관련 기획서는 추가로 정리해서 업로드하겠습니다! 
SLG 재화 요구량은 임시로 설정해뒀던 값이라 수정하고, 변경이 잦아서 헷갈리니까 한 눈에 보이도록 리스트 정리해서 함께 업로드하겠습니다.

**Comment by fkdl0048** [comment]
@Sumindd 저도 취향문제라고 생각되기는 하는데, 한번 크기를 줄인 버전으로 빌드를 뽑아봐도 좋을 것 같아요

**Comment by jeongopo** [comment]
SLG 필요작업
- 건설단계수정
- 다리건물 재화수정
- 아트리소스에 등록된것들중 오브젝트 교체, 씬연출추가 확인입니다

**Comment by fkdl0048** [comment]
@jeongopo 네네 맞습니다~!
