### ISSUE TITLE
[CH1] SLG 건설단계 수정, UI 수정

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#683]
20일 이후 작업예정인 SLG 추가 수정에 대하여 미리 이슈 정리합니다
~우선 29일 목표인데 길어지면 10/6까지 예정입니다.~
10/20 까지 작업예정입니다.

### 필요작업

- [x] 마마고 건물 건설중 단계 추가
- [x] 플로야드 다리 건설 단계 추가 #666
- [x] 마마고 컴퍼니 위치 변경 ([기획 변경 사항](https://drive.google.com/file/d/1sWEgaJ4GjkUAeMpIe3Uz5vsN4zVBKMsd/view?usp=sharing))
- [x] 오브젝트 F,G 상호작용 대사 적용 #691 

### 수정 필요사항 (241013 추가)
- [x] 메인 머지 후 이상없는지 테스트 (241014 완료)
- [x] 건설중 단계의 팝업아이콘 표시 (@JIJI037 지은님 스프라이트, @vprwolf 보민님 팝업아이콘)
- [x] SLG 마우스 커서 등장 효과음 추가 (#707 )
- [x] 대사 진행 후 조작 안켜지는 버그 (241014 추가)
- [x] 화살표 표시 방식 수정

### 추추가 수정 (241110 정리)

- [x] 화살표 표시 좌우로만 나타내도록 수정
- [x] SLG 팩 획득 시 럭키 위치 수정
- [x] 건설 스프라이트 수정

---

### 주요 변경 사항
**전체 공유사항**
- 마마고 컴퍼니 위치 변경에 따라, 연출, NPC 위치들이 모두 변경되었습니다
- 오브젝트 조이스틱, 다마고치와 마마고 건물 건설중 상호작용 대사가 추가되었습니다

**프로그래밍 리팩토링 공유사항**
- 런타임 중에 변경되는 상태 변화 제어를 위해 **SLGBuildingObject** 를 추가했습니다. (나중에 더 늘어난다면 그냥 ScriptableObject로 만들어버리는게 나을지도..)
- 기존에 분리해서 관리하던 빌딩관련 데이터들을 **SLGBuilding** 구조체를 통해 관리하도록 수정했습니다. (직접 제어는 SLGActionComponent 에서만 하도록 합니다)
![image](https://github.com/user-attachments/assets/54c92478-139c-4fd1-9e85-b2cdf93757c1)

- SubObjectSwitcher 클래스로 특정 오브젝트 하위의 오브젝트를 1개만 켜는 오브젝트를 관리하기 쉽도록 추가했습니다. (혹시나 쓰실 일이 있으시다면 쓰시면 좋습니당)
- 게임 프로세스와 빌딩 프로세스의 Enum 을 분리했습니다.
```
public enum SLGProgress
    {
        None = 0,
        AfterCutscene,
        ModeOpen, //SLG 처음 모드 오픈 (튜토리얼 진행)
        Proceeding,
        ModeClose, //SLG 모드 끝남
        Max
    }
public enum SLGBuildingProgress
    {
        None = 0, //Not Visible
        BeforeConstruct,
        Constructing, //Can Acceleate
        PlayCutScene,
        EndConstruct
    }
```
- 건설창을 건물 타입에 따라 표시되도록 공용화했습니다.

- **공용 FadeInOut 컴포넌트**를 추가했습니다. 기존에 우연님이 작업하셨던 FadeController 를 SpriteRenderer 로 제어하게 바꾼 정도입니다 혹시 쓰실일이 있으시다면 써주십사..

**작업하면서 든 생각..**
- Bridge.cs 없애도 되는지? 
- StageMover 의 좌표를 직접 넣는게아니라 Mover 끼리 호환되도록 하는건 어떨까,,
- 캐릭터의 콜리전 영역이 너무 크지않은가? 스테이지 옮길 때 너무 멀리서 옮겨지는느낌인데

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/3d16a440-26e4-4d15-acc6-76f8f2cdb2ce)

@Sumindd  npc들 위치랑 오브젝트위치 한번 확인부탁드립니다

레포지토리 변경때문인지 에디터 에러가 많은데 와중에 제 컴퓨터까지 상태가 이상해서 작업은 다음주에 이어서하겠습니다 ㅜ 

@fkdl0048  이번달 주말출근과 야근이슈가 있어서 작업 10/20 까지 연장해도될까요..ㅜ

**Comment by fkdl0048** [comment]
넵~

**Comment by Sumindd** [comment]
상단 제일 왼쪽 더미를 아래쪽으로 조금 당기는 게 좋을 것 같은데 기획상은 상관 없고 세부 위치는 아트 분들이 의견 주시면 좋을 것 같아요! 그리고 혹시나 해서.. 더미 하나가 줄더라도 마마고 컴퍼니 완공된 모습이랑 양옆 오브젝트랑 간격이 적당히 있으면 좋을 것 같아요 좀 좁아보여서..

**Comment by jeongopo** [comment]
원래가 훨씬 좁아서 제가 넓힌거긴한데요
위치 지정해주시면 수정해놓겠습니당

**Comment by Sumindd** [comment]
![image](https://github.com/user-attachments/assets/390c55f6-7127-42f5-9978-3dedfe0763ec)
이걸로 괜찮을지는 모르겠지만..
1. 위쪽 더미가 뒤쪽 회색길 거의 다 가릴 수 있게 내리기
2. 길을 약간 막더라도 지나갈 수 있는 여유만 된다면 괜찮으니 알투몬과 비슷한 라인에 오브젝트 배치하기
3. 왼쪽 돌 기둥과 마마고 컴퍼니 거리 여유롭게 이동하기 (만약 왼쪽 돌기둥 둘 자리가 좁다면 차라리 없애주세요. 마마고 컴퍼니 위치가 옮겨지면서 허전한 게 아니라면 오히려 돌기둥 없는 버전이 더 자연스러울 것 같기도 합니다.. )

근데 진짜로 미적인 부분이라 디테일한 위치 지정은 아트 분들이 확인해주셨으면 좋겠습니다.. 원래도 민지님이 해주셨던 작업으로 알고 있어서..

**Comment by jeongopo** [comment]
## 241013 작업내용
- SLG 관련 구조수정 .. 대부분의 플로우는 어느정도 정리된것같습니다 내일 회의끝나고 테스트 한번더해보고 올리겠습니다
거의 코드를 새로짜는수준으로 작업하게됐네요.. 😓 이래서 한번할때 잘해야..

### NPC, 오브젝트 위치 확인요청 (@Sumindd , @JIJI037 )
수민님이 정해주신 위치로 진행했는데 문제가 있어 제가 임시로 조정했는데 확인 부탁드립니다 

- **npc의 걸어가는 연출 시간으로 인해 파머와 알투몬을 먼 위치에 배치할 수 없어** 거리를 가깝게 하되 파머를 아래로 내렸습니다
- **연출 이동 경로 상 마마고가 걸쳐져서** 알투몬 위치는 더 올릴 수 없습니다
연출영상과 최종 위치도 첨부드립니다

https://github.com/user-attachments/assets/92c8be0d-b74d-49aa-89c6-c69905f4e1e0

![image](https://github.com/user-attachments/assets/c1cb2762-7eb7-4c8d-bfad-8e5aa555bdf9)



---
연출상으론 이게 최대배치인데 뒤쪽이 좀 허전한것같긴하네요 🤔
연출 고려해서 위치 다시 잡아주시면 수정하겠습니다~

> 위쪽 더미가 뒤쪽 회색길 거의 다 가릴 수 있게 내리기

더미 밑으로 내렸는데 제가 제대로 이해했는지 모르겠네요 

----

### 궁금해서해본 시간지나면 진짜 건설이 될까 모멘트

https://github.com/user-attachments/assets/1de7b228-fe5f-44cf-afd6-0726ed5e936f

**Comment by Sumindd** [comment]
제가 볼 땐 위치 괜찮은 것 같습니다! 빠른 건설도 실제로 되는 거 좋네요ㅎㅎ 나중에 꼭 업적 넣고 싶네요..

**Comment by jeongopo** [comment]
### 241014 작업내용
- main 브랜치에 병합했습니다. 우선 코드 상으로 봤을때엔 제대로 병합한것같은데 누락된거나 문제 있으면 알려주세요 (@wooyn730 , @vprwolf )

**플레이어 조작 멈추는 버그**
- 일단 쭉 테스트해봤을때 다른버그는 없는데 **글리치 나온 다음(or 럭키대화이후) 에 플레이어 인풋이 꺼진 상태로 남는 것 같습니다**
처음 럭키팩 줍고나서랑 SLG 럭키튜토리얼 끝나고 플레이어 인풋이 다시 활성화가 안됩니다. (다른 때에는 테스트 못해봄)
(오늘 빌드본에서 다들 별 말씀 없으셨던걸로 봐서는 제가 코드 병합을 잘못했을지도?)
확인해보니 ConnectionController.ActiveGlitch 에서 증가시킨 _playerInputEnableStack 카운트가 다시 감소하지 않던데 언제는 또 돌아오기도하더라고요

- 씬 넘어갈때 이슈가 있어서 우연님이 최근에 connection 관련 코드 수정하신 것 같던데, 우연님 병가시니 제가 알아서 다시 확인해보겠습니다. 오늘은 시간이 없어서.. 내일이나..목요일쯤

**Comment by jeongopo** [comment]
@Sumindd  @vprwolf  혹시 건설중일 때 건설창 헤더쪽 색상이라도 바꿀 수는 없을까요?
그냥 건설이랑 가속이랑 UI가 큰 틀에서 똑같고, 달라지는게 글씨들뿐이라서 멍하니 누르다보면 바뀐줄 모를것같아요 🤔

![image](https://github.com/user-attachments/assets/4f98369a-d58e-4df0-9f5d-fcfabc0b3058)
간단하게만 수정한다면 위에 여기 파란 영역이라도 다른 색으로 바꾼다거나 할 순 없을까요?

아직 바뀐걸로 빌드본 테스트 못해보셔서 의견 주시기 어려우실 것 같긴한데, 생각해주시면 감사하겠습니다 (_ _ )

**Comment by Sumindd** [comment]
건설 중간 단계 스프라이트 이미지 제작 후에 중간 단계 추가하면서 창이 연속으로 나오지 않아 괜찮을 것 같습니다.
[CH1 기획 변경 문서 15페이지](https://drive.google.com/file/d/1sWEgaJ4GjkUAeMpIe3Uz5vsN4zVBKMsd/view?usp=sharing) 확인해보시고 혹시 그래도 바뀌는 게 좋을 것 같은 상황이라면 보민님과 이야기 나눠서 색 변경하면 될 것 같습니다!

**Comment by Sumindd** [comment]
앗 그렇군요.. 그러면 확실히 색 바꾸는 쪽이 나을 것 같네요
보라색이나 녹색 중에 비슷한 톤으로 헤더 색만 바꿔서 가속 팝업 리소스 교체하면 좋을 것 같습니다. 보민님께 부탁드릴게요!
@vprwolf

**Comment by vprwolf** [comment]
적용할 때 어느 쪽이 좋을지 몰라 x버튼 색상도 바꾼 상태랑/x버튼 그대로인 상태 시안 잡아봤습니다!
보라색보다는 녹색쪽이 조금 더 눈에 띌 것 같아 녹색/노란색 시안으로 올려드립니다.
선택된 시안에 따라 에셋 추가하겠습니다!
![Frame 14](https://github.com/user-attachments/assets/9ccd60b5-dfe0-44fe-a1f1-d0a8b5d0bca5)

**Comment by roweclaw** [comment]
저는 녹색 좋을 거 같아요~
노란색은 통일성이 있어보이긴 하는데, 녹색이 확실히 눈에 잘 들어와서 보기 좋은 거 같아요!

**Comment by Sumindd** [comment]
SLG 화살표는 실시간 방향 변화 2초간 출력 -> 눌렀을 때 계산 값 기준으로 1초 출력으로 바꾸기로 결정했습니다.
그 외엔 페이드인 페이드 아웃 넣어서 깜빡이는 연출이라는 기존 기획서를 따라가면 될 것 같습니다! (단, 2회 출력 -> 1회 출력)

+본문에 기획 변경 사항 문서 링크 최신 버전이 아니길래 최신 버전으로 교체해뒀습니다!

**Comment by Songkihwa** [comment]
오.. 저는 통일성 있는 노란색이 편안해서 좋은 것 같긴한데 녹색도 좋으네요!

**Comment by wooyn730** [comment]
> 진짜 건설이 될까 모먼트

이거 게임 안하는 중에도 시간 흐르지 않나요?
24시간이 넘은 후에 게임을 접속한다면 어떻게 되나요 바로 연출이 나오나요?
(하지만 라플리가 맵3에 있지 않다면?)

> UI 색

일단 x버튼까지 함께 바뀐게 좋아 보입니다.
패널이 건설하기 / 건설중 / 마마고번역기구매 까지 3개이니 다 한번씩 써도 되지 않을까 싶어요!

근데 SLG팩, SLG하단 UI, 팝업까지 다 파란색으로 맞춘 걸로 알고있어서
더 통일감을 주려면 진한파랑이나 연한파랑은 어떨까 싶기도 합니다

**Comment by jeongopo** [comment]
@fkdl0048  안녕하세요..주중에 내내 야근을 하게되어 작업이 불가능한 컨디션이 되어서요 ㅜㅜ
혹시 버그 포함해서 다음주 10/1까지 작업해도될까요...? 8ㅅ8 죄송합니다

**Comment by fkdl0048** [comment]
넵 확인했습니다!

**Comment by jeongopo** [comment]
### 1101 작업내용

- 럭키 튜토리얼 중 커서 나올 때 사운드 적용

- 건설중 건물 추가.. 근데 아웃라인이 흐립니다,, @JIJI037 
![image](https://github.com/user-attachments/assets/917abb91-d6ec-45de-afcd-c89c2844381a)

- 화살표 방향 처음에만 제어되도록 수정
회의때 설명드렸다시피 2D에서 회전값 계산 과정에서 좌우로 흔들리는것이기 때문에 
**회전을 주는 순간부터 오브젝트에 붙는 화살표가 아예 안흔들릴수는없습니다..** 
그래도 계속 회전시키던거보단 덜 흔들리는거에 의미를 두는것으로...


https://github.com/user-attachments/assets/830ed0e2-3d1b-435e-a94e-21928e6f3879


아래는 코드 안넣고 그냥 회전된 화살표가 붙어있을때의 모습을 비교를 위해 넣어드립니다

https://github.com/user-attachments/assets/ff208015-1dcb-4752-bd7f-3c6249235fdd

코드 제어의 문제가 아니라 회전을 주는것 자체에서 흔들림이 발생하는 것입니다.. 흑흑
3D 오브젝트가 아니다보니 좌표계 하나가 없어져서 생기는문제가아닐까 추측해봅니다 흠
흔들리는게 많이 거슬리신다면,, 회전값 아예없이 왼쪽오른쪽만 표시하는수밖에..

**Comment by Sumindd** [comment]
주요 기능보단 퀄리티와 편의성을 위한 부가 기능이라 왼쪽 오른쪽만 구분해서 표시하는 게 나을 것 같습니다 
고생이 많으시네요ㅜㅜ

**Comment by JIJI037** [comment]
아웃라인 흐린 거 수정해 구드에 올렸습니다 또 문제 생기시면 편하게 말씀주세요!!

**Comment by Sumindd** [comment]
메모 정리하다가 예전에 현정님이 요청하셨던 걸 이제야 발견했네요.. 죄송합니다ㅠ
플로야드 브릿지 중간 과정 추가하실 때 시간 단축 비용은 6시간에 25코인으로 설정 부탁드립니다!

**Comment by jeongopo** [comment]
### 1110 작업내용

- 플로야드 브릿지 시간 재화 수정
![image](https://github.com/user-attachments/assets/d16cf294-2d1a-4634-b226-44780a028108)

- 건설중 스프라이트 변경 (외곽선 깔끔해져서 좋네욥)
![image](https://github.com/user-attachments/assets/24b839c5-cbb4-402a-a36c-6eafd125d246)

- 화살표 표시 좌우로만 하도록 수정

https://github.com/user-attachments/assets/1b5f6b15-5683-4441-bbb5-8cf3273500b4

- 럭키 등장 위치 수정
![image](https://github.com/user-attachments/assets/a99aea28-bc2d-40b7-b33b-0c2b6308c156)

**Comment by Sumindd** [comment]
화살표가 확실히 깔끔해져서 좋네요
다른 부분도 대부분 정리된 것 같아서 SLG는 빌드로 최종 점검만 해보면 될 것 같아요!

**Comment by jeongopo** [comment]
우연님께 전달드리긴했는데
건설중일때 팝업 아이콘 다르게 하는 이슈도 있었던것같은데 그것도 한번 확인부탁드립니당

**Comment by Sumindd** [comment]
건설 중간 단계에서 말풍선 속 아이콘 바꾸는 거 말씀하시는 건가요? 
바꾸면 좋을 것 같긴한데 아마 전에 얘기가 따로 나오진 않았던 것 같아요 내일 회의에서 얘기해보면 될 것 같습니다!

**Comment by jeongopo** [comment]
아하 그렇군요 제가 다른거랑 착각한 모양입니다 ㅎㅎ... 감사합니다~

**Comment by jeongopo** [comment]
이거닫고 #708 로 대응하겠습니다
