### ISSUE TITLE
[CH2] 위자드 스톤(TCG) 개발

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#803]
### 작업
- ===1주차===
- [x] 위치 UI 전체화면에 적용
   - `DOAnchorPos`를 사용 못하는 문제 => 업데이트도 하고 asmdef 만들었더니 된다 ㅠㅠㅠㅠㅠ
- [x] 장소 이동 시 다른 장소 이동 클릭 막기
   - `BtnTxtColorChanger`도 함께 수정
- [x] `Nobody` 구현
   - 임시로 처리해뒀던 부분 찐 구현
- [x] CH2 치트 (Turn1부터, Turn2부터)
   - <<StartLocation(시작하는 장소변환)>>과 <<SetLocation(넘어가는 장소변환)>>을 임의로 설정해놔서... 이거 수정 필요....
- ===2주차===
- [x] 타이틀에 설정 버튼 2개임
- [x] SLG 폰트 해상도 체크 ([링크](https://github.com/GG-Studio-990001/Grayed-Game/issues/796) 하단 참고)
- [x] BGM 적용 ([사운드 삽입 구간](https://docs.google.com/spreadsheets/d/1rRibyJ3_OrO2Rrk3fZ_K0i2Fmqud4fElIb-DMgHCYcs/edit?gid=1190940976#gid=1190940976), [사운드 리소스 리스트](https://github.com/GG-Studio-990001/Grayed-Game/issues/782)) (루프 유무는 아직 ...)
- ===3주차===
- 대사 폴리싱 버전 적용
   - [x] Turn0
   - [x] Turn1
   - [x] Turn2
   - [x] TCG
- [x] BGM 적용2 (6, 7)
- [x] CH2 캐릭터 늘린 걸로 교체
- [x] CH2 배경 러프 적용
- ===4주차===
- [x] BGM4 수정된 버전 적용
- [x] Turn1~3 임시 일러스트 추가
- [x] 나머지 대사 폴리싱 버전 적용
- [x] Turn0~3 치트 데이터 교체 (Tcg 변수 추가됨)
- ===
- [ ] Fade 되는 동안 아무것도 누를 수 없게 처리
- [ ] CH1 마지막 알투몬 도망 속도 조절

## TCG 개발
- #798 
### 작업
- ===1주차===
- [x] CH2 씬에 이식
   - Turn2의 질문 1, 2까지 적용 확인
- [x] 세이브 기능 구현
   - 현재 턴수만 저장 후 턴수에 따라 S 이벤트 다이얼로그가 출력되게 구현 (필요하다면 턴수과 위치로 진행중인 N이벤트부터 출력하도록..?)
- ===2주차===
- [x] UI 숨김 기믹 구현1 => TCG팩 발견 & 럭키 설명 (Turn0) [참고](https://github.com/GG-Studio-990001/Grayed-Game/issues/802)
- [x] UI 숨김 기믹 구현2 => 슈아브팩 발견 & 접속 (Turn2)
- [x] 호감도 최소 0 (마이너스 X)
- ===3주차===
- [x] 비주얼 노벨 UI 적용
   - [x] pressed
- [x] TCG UI 적용 & 카드 이쁘게
   - [x] 호감도 UI
- [x] 카드 연속클릭 방지
- [x] 답변 라인 뷰에 출력하기
- [x] TCG시 비주얼노벨 UI 숨김
- 애니메이션 구현
   - [x] 미카엘이 가운데로 이동
   - [x] 호감도 상승/하락
   - [x] 호감도 하트 두근두근
   - [x] 카드 올라가기/내려가기
   - [x] 선택된 카드 Fade
   - [x] 마우스 호버 시 카드 확대
   - [x] 카드 선택하면 더이상 호버 안되게
- ===4주차===
- [x] UI OFF에서 UI OFF 아이콘도 안 보여야 함. 다시 활성화 하는 방법은 아무데나 클릭하기 (수민)
- [x] 카드 선택하면 바로 카드 축소
- [x] 미카엘 질문 말풍선 사라질 때, 페이드 주기 (수빈)
- [x] 선택한 카드 사라지기, 미카엘 우측 이동을 동시에 하기 (수빈)
- Turn3 구현
   - [x] 장소 설정
   - [x] NPC 등장
   - [x] BGM 설정
   - [x] 슈아브와 Turn3 연결
- 카드 애니메이션 ([참고](https://www.youtube.com/watch?v=Xo7EEegTUfE))
   - [x] 카드 4개 들고 있을 때 펼쳐지는 각도 (1~3은 추후 처리)
   - [ ] 카드가 날아와 펼쳐지기

++
보완
- 스페이스바로 럭키 대사 넘기기 안됨
- 주민 말할 때 파머 하이라이트 끄기
- StartLocation SetLocation 처리
- 자동진행중에 UI 숨김 했는데 대화창 뜸...
- TCG팩 획득시 럭키 말풍선 위치 전체모드일 때 이상함
- UI숨김 기믹 장소 이동할 때 클릭하면 게임 멈춤

작업 예정
- UI숨김&자동진행 점검, NPC 2명 이상 스탠딩 위치 처리
- 나머지 Turn 진행, 표정 변경 등 / 글리치 효과 고민(다른 걸로) / 오프닝 구현 / TCG 럭키 훈수 )

---

### TCG와 라인뷰 섞어쓰기
현재
미카엘 질문 => 카드 선택 => 선택된 카드만 보여주기 => 미카엘 반응&호감도 변화 => 다이얼로그 이어서

목표
미카엘 질문 => 카드 선택 => 선택된 카드만 보여주기 => **카드 내용이 라인뷰에 출력(카드가 답변으로 변함) => 호감도 변화 => 미카엘 반응 라인뷰에 출력** => 다이얼로그 이어서

라플리의 대사인 답변(카드 내용)과 미카엘의 대사인 반응이 라인 뷰로 출력되어야 함.
csv 파일 대사를 바로 얀 스피너에 적용시킬 수 있는 방법이 있을까?
없다면 방법도 없진 않음
직접 7개 질문에 대한 답변과 반응을 얀 스피너에 적어서 if문으로 처리하면 될 것 같긴 함...

**=> 노가다 안쓰는 방법으로 해결 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 너무 힘들어따**

### UI 숨김 기믹
![image](https://github.com/user-attachments/assets/5c4ba81c-3869-4328-a64f-c8eca49fbe26)
대화창 뒤에 아이템 숨겨두는 걸 1에서 해야할까 2에서 해야할까?
1에서 한다면 뒤의 대사는 캔슬? 문제 없을까?
2에서 한다면 개발은 편한데 개연성?이 없달까... 일단 2로 개발

---

### 효과 순서
0 미카엘이 가운데로 이동한다
1 미카엘 버블 활성화 +질문 띄우기
2 카드 덱이 올라오고 카드 4장이 날아온다 (두 번째 질문부터는 카드 3장은 아래서 위로 올라오고, 이후 카드 1장만 날아온다)
2-1 마우스 오버를 하면 카드가 확대된다
3 카드 1장을 선택하면 해당 카드만 남고 나머지 카드+카드 덱은 아래로 내려간다
4 카드가 페이드로 사라지고 라플리 답변이 출력된다
5 미카엘 버블이 사라지고 미카엘 반응이 출력된다.
5-1 상단에는 미카엘 호감도바가 보이며 호감도에 변화가 있다면 상승/하락한다 (+상승/하락 효과음)
5-2 하트가 두번 뛴다
6 호감도바가 사라진다
7 다음 다이얼로그를 진행한다

### 작업 순서
1 미카엘 반응을 라인뷰에 출력하는 방법 모색

### 이상한 점/고민
- 라인뷰랑 섞어쓰기는 성공했는데 직후에 출력되는 다이얼로그 1 3번째 줄이 씹힘.. 엥;ㅠ
- 시스템 기획서를 보긴 했는데 라플리 나오고 미카엘 원위치하고 대화창 뜨는 게 낫지 않을까? 근데 그러면 카드가 답변으로 변하는 연출이 애매함
- 미카엘이 키가 커져서 미카엘 머리 위에 호감도창을 띄우기 애매해져서 임의로 위치 조정함

**Comment by wooyn730** [comment]
호감도 최소 0
마이너스 X
max 100

**Comment by wooyn730** [comment]
## 두근두근

https://github.com/user-attachments/assets/6e398db0-c489-4120-b814-8e846ecb97ab


https://github.com/user-attachments/assets/834c1105-f5f2-4c45-94f0-4a222cdddf65


https://github.com/user-attachments/assets/b03d12bf-c4e2-4f44-b0ec-6c88d036f1d1


https://github.com/user-attachments/assets/6063752c-6087-43f5-a6f8-caf2fa1ac547


일단 4번으로 픽
별로거나 더 좋은 거 있으면 바꿀듯..

**Comment by Sumindd** [comment]
1번, 4번이 깔끔한 것 같네요!

**Comment by wooyn730** [comment]
@roweclaw 
![image](https://github.com/user-attachments/assets/4e27f2af-cc11-483a-b330-570e6f7bd475)

Turn3에 BGM7이라 적힌 부분 6을 잘못 쓰신 것 같아요.
그리고 초반에 알투몬 등장하는데 알투몬 테마곡 안나오나요?

**Comment by wooyn730** [comment]
[v0.5.1](https://drive.google.com/file/d/137_vigx_Y-L6OIaXpc2nBGmspOY9_bgr/view?usp=drive_link)

**Comment by roweclaw** [comment]
BGM6으로 수정했습니다~
알투몬 테마곡은 이미 이전 Turn에서 알투몬이랑 같이 있었기에 따로 추가하지 않았었는데요
빌드로 확인해보니까 있어도 괜찮을 것 같네요! 확인 감사합니다!! 👍

**Comment by wooyn730** [comment]
https://github.com/user-attachments/assets/e829c3fa-d1a6-4e4b-84e4-feb4c940f290

**Comment by wooyn730** [comment]
빌드 피드백

- 드로우 하기 전에 다른 카드를 클릭해서 사용하면 드로우 한 카드와 함께 사용 애니메이션(페이드 아웃)이 적용 됨.
- TCG팩 접촉하는 파트에서 UI숨김 껐다 켜면 그 이후로 계속 UI숨김 버튼 제외한 UI가 모두 사라짐
- -10인데 게이지 올라감
